### ISSUE TITLE
stream: issues with movie playback

### ISSUE THREAD

**Issue by ehalmkro** [DianaMukaliyeva/hypertube#106]
Movie playback is not working consistently on all users after the initial 20mb chunk. I myself have not been able to reproduce. I made a branch that removes the chunking, [`backend/remove_chunk`](https://github.com/DianaMukaliyeva/hypertube/tree/backend/remove_chunk). Feel free to test that and see if you have any differences on the behaviour.

Tested the backend endpoint `/api/movies/{imdbCode}/play/{token}` and the filestream worked flawlessly with both chunking and non-chunking backend. The front end `react-video-js-player` based player also seems to work on my end with both `backend/remove_chunk` and `backend/stream_logic` branches' backends. 

I suggest you all try both the front end player and the 'raw' browser rendered filestream from the endpoint with the two branches.

How do you interact with the player @DianaMukaliyeva & @lapaset ? I press the big centered play button at first and then press play on the bottom left button to start the stream. This could also have something to do with the issue.

### Issues and observations:

> I tried different videos and the result varies. For me it can be also the first chunk that is less than 20MB when play starts. Here are my observations:
> - If the loaded chunk is below 20MB the video stops when it's reached and loading seems to stop in the network tab
> -> If I start the video again it will not get beyond that same spot
> -> However when I open the video in my local videoplayer it has the parts that are missing
> - When I refresh and play the video again it may or may not load the missing parts
> - Sometimes after a couple restarts 20MB chunks start loading. In that case everything works smoothly
> - Video player shows the file as fully downloaded even when it is not
> -> Could the problem be that it is trying to play something that does not exist?
> - VSCode shows the video size as the size of the complete file even when it is not loaded

_Originally posted by @lapaset in https://github.com/DianaMukaliyeva/hypertube/pull/95#discussion_r602103473_

> I checked today. I am receiving 206, and it's size is not stable. First response grows until 20 MB, and next one is freeze somewhere about 6-8 MB.
> Each movie is playing only first 3-10 minutes.
> Could @iljaSL , @T7Q , @lapaset also check this one? Do you have this problem? (I can not watch the whole movie, it always stops somewhere in 3-10 minutes after play, even if movie is loaded completely).

_Originally posted by @DianaMukaliyeva in https://github.com/DianaMukaliyeva/hypertube/pull/95#discussion_r601872569_

**Comment by DianaMukaliyeva** [comment]
Yes, I am also interacting with the player by clicking the button in the center and then the play button. But on the frontend, we are using `react-player` based player. When you are testing with the frontend, do you delete a folder with movies on the backend before testing, or maybe you have a very fast internet connection?
Actually, I think I have some working version, I will push it later, after testing it out.

**Comment by ehalmkro** [comment]
I guess the issue could very well be that the backend is trying to stream a part of the movie that has not downloaded yet. I've tried with both completed and uncompleted movies. My internet speed is 100/100mbps so the download can usually keep up with the player, given the 20mb lead, especially with the minimum seed count that we have.

**Comment by DianaMukaliyeva** [comment]
Created new branch `backend/fix-stream`. The movie stream should work, if not loaded yet - should show some error. Still in the developing phase, but could be tested.

**Comment by T7Q** [comment]
I also have a problem reported in issue #95, the new branch by @DianaMukaliyeva seem to solve it, I’ll keep testing

**Comment by lapaset** [comment]
Sorry Esa, i didn't notice your question yesterday. I'm also interacting with the player the same way you are. Pulled Diana's fixes and player seems to work for me now!

**Comment by ehalmkro** [comment]
Awesome work @DianaMukaliyeva , and thank you all for testing stuff! @DianaMukaliyeva , when you're done with the feature, you could merge it to `backend/stream_logic` so we could have a single PR for all the backend fixes.

**Comment by DianaMukaliyeva** [comment]
It was done together with @T7Q :dancing_women:

**Comment by ehalmkro** [comment]
The dynamic duo, of course! Thank you both then! 🎉
