### ISSUE TITLE
Firefox: Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by iljaSL** [DianaMukaliyeva/hypertube#93]
How to reproduce:  Press play to play the movie while it's downloading, and press after it straight stop.  The following error will be displayed 

`Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.`

Looks like a async issue. This error does not appear on chrome.

**Comment by DianaMukaliyeva** [comment]
I am also having this issue, but I don't know if we can fix it. I couldn't find how we can handle it, I think it has to do with how the react-player handle play and pause 🤪 , but maybe I am wrong.

**Comment by T7Q** [comment]
same issue here... it must be play-pause. There is nothing to pause as the video is still buffering. There must be a param we could use to see if the video is buffered or not and prevent the pause... or not show controls if buffering???
